Newframework
DigitalShoestringSolutions/TemperatureMonitoringStarterSolution pull request #1
Opened 2023-11-03 16:00 UTC by chen2181

new framework, fix some bugs, remove some files to be consist with new framework

2023-11-09 11:28 UTC, Greg-Hawkridge commented
Have you checked installation on a device?

2023-11-09 11:32 UTC, Greg-Hawkridge requested changes

2023-11-09 11:32 UTC, Greg-Hawkridge commented on start.sh
- [ ] Checked for ambient temperature
- [ ] Checked for process temperature
- [ ] Checked for equipment temperature

2024-01-25 16:49 UTC, chen2181 commented on start.sh
this is resolved and ready

2024-01-25 16:53 UTC, Greg-Hawkridge approved these changes

2024-01-25 16:54 UTC, merged